FileVersion = 1
Dependencies = {corlib = "*", SDL2 = "*", MiniZ = "*", ImGui = "*", ImGuiImplSDL = "*", ImGuiImplOpenGL3 = "*"}

[Project]
Name = "Strawberry"
TargetType = "BeefLib"
StartupObject = "Program"
