FileVersion = 1
Dependencies = {corlib = "*", SDL2 = "*", Strawberry = "*"}

[Project]
Name = "SampleGame"
TargetType = "BeefGUIApplication"
StartupObject = "Strawberry.Sample.Program"
DefaultNamespace = "Strawberry.Sample"
