FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["c:\\Users\\Matt\\Documents\\Projects\\Strawberry\\src\\Static\\Ease.bf", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Action.bf", "c:\\Users\\Matt\\Documents\\Projects\\Strawberry\\SampleGame\\src\\MovingJumpThru.bf", "c:\\Users\\Matt\\Documents\\Projects\\Strawberry\\SampleGame\\src\\Player.bf", "c:\\Users\\Matt\\Documents\\Projects\\Strawberry\\src\\Struct\\Color.bf", "c:\\Users\\Matt\\Documents\\Projects\\Strawberry\\SampleGame\\src\\Level.bf", "c:\\Users\\Matt\\Documents\\Projects\\Strawberry\\src\\Physics\\JumpThru.bf", "c:\\Users\\Matt\\Documents\\Projects\\Strawberry\\src\\Components\\Timer.bf", "c:\\Users\\Matt\\Documents\\Projects\\Strawberry\\src\\Physics\\Actor.bf", "c:\\Users\\Matt\\Documents\\Projects\\Strawberry\\src\\Physics\\Solid.bf"]

[MainWindow]
X = 64
Y = 64
Width = 1200
Height = 1024
ShowKind = "Maximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 500.0
RequestedHeight = 350.0
SizePriority = 350.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 350.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 111.7143
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 150.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Action.bf"
TabWidth = 89.14286
Type = "SourceViewPanel"
FilePath = "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Action.bf"
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Ease.bf"
TabWidth = 78.85714
Type = "SourceViewPanel"
FilePath = "c:\\Users\\Matt\\Documents\\Projects\\Strawberry\\src\\Static\\Ease.bf"
CursorPos = 206
ProjectName = "Strawberry"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "MovingJumpThru.bf"
TabWidth = 151.4286
Type = "SourceViewPanel"
FilePath = "c:\\Users\\Matt\\Documents\\Projects\\Strawberry\\SampleGame\\src\\MovingJumpThru.bf"
CursorPos = 406
ProjectName = "SampleGame"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Color.bf"
TabWidth = 83.42857
Type = "SourceViewPanel"
FilePath = "c:\\Users\\Matt\\Documents\\Projects\\Strawberry\\src\\Struct\\Color.bf"
CursorPos = 588
ProjectName = "Strawberry"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Timer.bf"
TabWidth = 85.14286
Type = "SourceViewPanel"
FilePath = "c:\\Users\\Matt\\Documents\\Projects\\Strawberry\\src\\Components\\Timer.bf"
CursorPos = 530
VertPos = 130.0
ProjectName = "Strawberry"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Actor.bf"
TabWidth = 82.85714
Type = "SourceViewPanel"
FilePath = "c:\\Users\\Matt\\Documents\\Projects\\Strawberry\\src\\Physics\\Actor.bf"
CursorPos = 2066
VertPos = 2522.0
ProjectName = "Strawberry"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "JumpThru.bf"
TabWidth = 109.1429
Type = "SourceViewPanel"
FilePath = "c:\\Users\\Matt\\Documents\\Projects\\Strawberry\\src\\Physics\\JumpThru.bf"
CursorPos = 1409
VertPos = 1430.0
ProjectName = "Strawberry"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Solid.bf"
TabWidth = 81.71429
Type = "SourceViewPanel"
FilePath = "c:\\Users\\Matt\\Documents\\Projects\\Strawberry\\src\\Physics\\Solid.bf"
CursorPos = 174
ProjectName = "Strawberry"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Controls.bf"
TabWidth = 90.57143
Type = "SourceViewPanel"
FilePath = "c:\\Users\\Matt\\Documents\\Projects\\Strawberry\\SampleGame\\src\\Controls.bf"
CursorPos = 433
ProjectName = "SampleGame"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Player.bf"
TabWidth = 76.85714
Type = "SourceViewPanel"
FilePath = "c:\\Users\\Matt\\Documents\\Projects\\Strawberry\\SampleGame\\src\\Player.bf"
CursorPos = 2419
VertPos = 2180.5
ProjectName = "SampleGame"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Level.bf"
TabWidth = 72.85714
Type = "SourceViewPanel"
FilePath = "c:\\Users\\Matt\\Documents\\Projects\\Strawberry\\SampleGame\\src\\Level.bf"
CursorPos = 190
ProjectName = "SampleGame"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "SampleGame.bf"
TabWidth = 118.0
Type = "SourceViewPanel"
FilePath = "c:\\Users\\Matt\\Documents\\Projects\\Strawberry\\SampleGame\\src\\SampleGame.bf"
CursorPos = 169
ProjectName = "SampleGame"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Program.bf"
TabWidth = 92.28571
Type = "SourceViewPanel"
FilePath = "c:\\Users\\Matt\\Documents\\Projects\\Strawberry\\SampleGame\\src\\Program.bf"
CursorPos = 166
ProjectName = "SampleGame"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 437.0
RequestedHeight = 327.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 437.0
RequestedHeight = 437.0
SizePriority = 2558.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Memory"
TabWidth = 98.0
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 84.28571
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Auto"
TabWidth = 76.28571
Type = "AutoWatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 437.0
RequestedHeight = 437.0
SizePriority = 2558.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 114.5714
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 94.0
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 102.0
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 109.4286
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 88.85714
Type = "OutputPanel"

[DebuggerDisplayTypes.""]
IntDisplayType = "Default"
MmDisplayType = "Default"
