FileVersion = 1
Dependencies = {corlib = "*", Strawberry = "*"}

[Project]
Name = "SampleGame"
TargetType = "BeefGUIApplication"
StartupObject = "Strawberry.Sample.Program"
DefaultNamespace = "Strawberry.Sample"

[[Project.DistinctOptions]]
Filter = ""
ReflectAlwaysInclude = "IncludeAll"
